# Generated by Django 4.2.3 on 2023-08-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='taxa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa (%)'),
            preserve_default=False,
        ),
    ]
