# Generated by Django 4.2.3 on 2023-08-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_invoice_payment_date_alter_person_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
