# Generated by Django 4.2.3 on 2023-08-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_paymenttype_taxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='taxa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa (%)'),
        ),
    ]
