# Generated by Django 4.2.3 on 2023-08-21 00:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scheduleevent__client'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 8, 20)),
        ),
        migrations.AddField(
            model_name='invoice',
            name='generator_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sale'),
        ),
    ]
