# Generated by Django 4.2.3 on 2023-08-22 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_person_email_remove_person_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='installments1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='installments2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='price1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
    ]
