# Generated by Django 4.2.3 on 2023-08-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_scheduleevent_sale_alter_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='is_cortesy',
            field=models.BooleanField(default=False),
        ),
    ]
