# Generated by Django 4.2.3 on 2023-08-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_scheduleevent_is_cortesy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleevent',
            old_name='is_cortesy',
            new_name='is_courtesy',
        ),
    ]
