# Generated by Django 4.2.3 on 2023-08-24 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_is_cortesy_scheduleevent_is_courtesy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleevent',
            name='_client',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='service',
        ),
        migrations.RemoveField(
            model_name='scheduleevent',
            name='sessions',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.date(2023, 8, 24)),
        ),
        migrations.AlterField(
            model_name='scheduleevent',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
